# Generated by Django 2.2.2 on 2019-07-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videocollectionorder',
            unique_together=set(),
        ),
    ]
