# Generated by Django 2.2.2 on 2019-10-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190705_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='gif_preview',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
