# Generated by Django 2.2.2 on 2019-06-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190606_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='upload',
        ),
        migrations.AddField(
            model_name='video',
            name='collections',
            field=models.ManyToManyField(related_name='videos', to='video.VideoCollection'),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='VideoUpload',
        ),
    ]
