# Generated by Django 2.2.2 on 2019-06-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20190608_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='raw_video_file',
            field=models.FileField(null=True, upload_to='protected/video/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
