# Generated by Django 2.2.2 on 2019-10-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20191012_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoplaybacktracker',
            name='seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
