# Generated by Django 2.2.8 on 2020-01-04 02:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('video', '0007_videotag'), ('video', '0008_video_tags')]

    dependencies = [
        ('video', '0006_auto_20191013_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', to='video.VideoTag'),
        ),
    ]
