# Generated by Django 2.2.2 on 2019-06-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190609_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='raw_video_file',
        ),
    ]
