# Generated by Django 2.2.2 on 2019-06-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_remove_video_raw_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCollectionNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.VideoCollection')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            options={
                'unique_together': {('collection', 'number')},
            },
        ),
    ]
