# Generated by Django 2.2.2 on 2019-06-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_videocollectionnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocollectionnumber',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
