# Generated by Django 2.0.6 on 2019-03-01 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2019, 3, 1, 0, 4, 36, 587214, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
