# Generated by Django 2.0.6 on 2019-03-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190314_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='private',
        ),
        migrations.AddField(
            model_name='videoupload',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
