# Generated by Django 2.0.6 on 2019-02-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190212_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='upload_id',
            field=models.CharField(default='aaa', max_length=50),
            preserve_default=False,
        ),
    ]
