# Generated by Django 2.0.6 on 2019-02-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_videofile_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='upload_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
