# Generated by Django 2.0.6 on 2019-03-07 01:31

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190301_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_info', models.TextField(null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='upload_info.title', unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_id', models.CharField(max_length=50, null=True)),
                ('master_playlist', models.FileField(null=True, upload_to='')),
                ('thumbnail', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='master_playlist',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.VideoCollection'),
        ),
        migrations.AlterField(
            model_name='videovariant',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='video.Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.VideoUpload'),
        ),
    ]
