# Generated by Django 2.0.6 on 2019-02-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20190213_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='thumbnail',
            field=models.FilePathField(default=None, null=True),
        ),
    ]
