# Generated by Django 2.0.6 on 2019-02-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_videofile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='header',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
