# Generated by Django 2.0.6 on 2019-03-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_folder_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vid_info',
            new_name='vid_info_str',
        ),
        migrations.AlterField(
            model_name='video',
            name='folder_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
