# Generated by Django 2.0.6 on 2019-02-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_videofile_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='header',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
