# Generated by Django 2.0.6 on 2019-02-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20190213_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='task_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
