# Generated by Django 2.0.6 on 2019-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20190307_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='processing_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
