# Generated by Django 2.0.6 on 2019-03-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20190308_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='collection',
        ),
        migrations.AddField(
            model_name='videoupload',
            name='collection',
            field=models.ManyToManyField(related_name='videos', to='video.VideoCollection'),
        ),
    ]
