# Generated by Django 2.0.6 on 2019-03-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20190310_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoupload',
            old_name='collection',
            new_name='collections',
        ),
    ]
